### ISSUE TITLE
Use this in my own project without typescript and NUnit

### ISSUE THREAD

**Issue by khuberts** [Steve-Fenton/SeleniumSuperDriver#4]
Hi,

I want to use this functionality in my own project so i can run my tests in multiple browsers at the same time.

Regards,

Kelvin

**Comment by Steve-Fenton** [comment]
If you add SuperDriver to your project using NuGet, you'll see that it only contains the DLLs.

https://www.nuget.org/packages/Fenton.Selenium.SuperDriver/

```
PM> Install-Package Fenton.Selenium.SuperDriver 
```

The TypeScript / NUnit parts in the GitHub repo are just to help demonstrate the usage, they aren't part of the library itself. The only dependency is Selenium.Support, which NuGet will automatically get for you if you don't already have it.

**Comment by khuberts** [comment]
But i only want to use the superwebdriver. Do i then have to use all the files in the substitutes folder?

**Comment by Steve-Fenton** [comment]
The NuGet package only contains:
- Fenton.Selenium.SuperDriver.dll

The substitutes are all packaged in there. They are needed as they maintain the facade that you are dealing with a single browser, whether you have 1 or 10 browsers actually co-ordinated within the SuperDriver. For example, although SuperDriver allows you to believe you have a single web element, it is actually keeping tabs of one web element per browser - that is what the substitutes make possible.

The substitutes are not related to NUnit, or to testing - they are part of the implementation.
