### ISSUE TITLE
ExecuteScript missing

### ISSUE THREAD

**Issue by GrumpyMeow** [Steve-Fenton/SeleniumSuperDriver#5]
Most WebDrivers support ExecuteScript nowadays. The absence of this method on the SeleniumSuperDriver is probably because the IWebDriver does not have the ExecuteScript method.
At this time this means the SuperWebDriver does not suit my specific needs.
Nevertheless. Thank you for creating this project. Maybe in the future i can add the method myself.

**Comment by Steve-Fenton** [comment]
Pull requests are welcome :)
