### ISSUE TITLE
Issue when using SuperDriver with manage() of IOptions

### ISSUE THREAD

**Issue by tjnhdo** [Steve-Fenton/SeleniumSuperDriver#6]
Hi Steve,
Firstly, Thanks so much for SuperDriver solution which is helpful with my project.
However, when we use it with selenium webdriver 2.53, We saw issue between SuperDriver and IWebdriver. Error message displays when you use manage() of IOptions with SuperDriver. You can use current project, upgrade Selenium Webdriver and see this issue.

If you need screenshot or any information from me. Please let me know.

Thanks and Best Regard,
Tinh.Do

**Comment by Steve-Fenton** [comment]
v0.2.0.0 uses the latest Selenium packages. There were a few interface changes in Selenium that required the substitution classes to be updated.
